source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target ‘CBCP’ do
    pod 'AFNetworking', '~> 3.1.0’
    pod 'MJRefresh', '~> 3.1.12’
    pod 'Masonry', '~> 1.0.2’
    pod 'SDWebImage', '~> 3.8.2'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'SVProgressHUD'
end
